name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/setup@v3
        with:
          version: next-12
          cache: true
      - name: Run prettier
        run: pnpm prettier --check --config .prettierrc 'README.md|*.json|*.yaml|*.yml|(skins|cypress|.github|extensions)/**/*.{css,js,json,ts,vue,yaml,yml}|extensions/GbSessionProvider/**/*.php'
